### ISSUE TITLE
Criar estratégias de melhorias para a produção do Cuida

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#166]
## **Objetivo**

**Como** equipe de produção do Cuida  
**Quero** participar de novas estratégias para o desenvolvimento do Cuida  
**Para** colaborar com ideias e melhorias 

## **Contexto**

- O Cuida! é o boletim informativo semanal feito através da coleta dos fatos, links e sugestões do cotidiano do NIT e do Felicilab, e que circula sempre às segundas-feiras nos canais internos do telegram. Também é publicado no instagram, fazendo um recorte para os acontecimentos que podem ser divulgados. Após mais de 20 edições e feedbacks de colaboradores do time, fizemos uma reunião na sexta-feira (23) de alinhamento e definição de algumas ações de melhoria. 

## **PubliciLab**

- [ ] Produzir um Media Training
- [x] Organizar o processo de gravação do Cuida presencialmente
- [x] Levantamento de equipamentos (áudio e vídeo)

## **Critérios de Aceitação**

- [x] Criar estratégias de melhorias para o Cuida  
**Dado que** sou da equipe de produção do Cuida
**Quando** crio novas estratégias de melhoria 
**então** aumento a qualidade do Cuida

## Observações
Links de apoio e informações adicionais

**Comment by danielgula** [comment]
Criamos uma rotina de gravar o Cuida todas às segundas-feiras, às 14h na sala de controle do auditório da ESP.

**Comment by Clarisse1983** [comment]
Tarefa concluída em parte. Para frente, avaliação do formato atual e ressignificação do Cuida.
