### ISSUE TITLE
Realizar ações de comunicação - Setembro/21

### ISSUE THREAD

**Issue by anapvcv** [EscolaDeSaudePublica/FeliciLab#193]
## **Objetivo**

**Como** integrante do Publicilab
**Quero** realizar ações de comunicação
**Para** divulgar as atividades e ações do Felicilab

## **Contexto**

- Ações de comunicação a serem realizadas em setembro através do Laboratório de Inovação da Escola de Saúde Pública do Ceará - FeliciLab.

## **Publicilab**

**Semana 6/09 até 10/09**
- [ ] Cuida
- [ ] Release Prêmio de Inovação
- [ ] Oficina OBS
- [ ] Liberou Geral

**Semana 13/09 até 17/09**
- [ ] Cuida 
- [ ] Drops da Semana de Inovação
- [ ] Prêmio de Inovação
- [ ] Liberou Geral 

**Semana 20/09 até 14/09**
- [ ] Cuida
- [ ] Drops Semana de Inovação
- [ ] Liberou Geral 

**Semana 27/09 até 1/10**
- [ ] Cuida 
- [ ] Vídeo dos depoimentos - Oficina de Design Thinking
- [ ] Liberou Geral 

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** eu quero comunicar as ações do Felicilab 
**Quando** executo o planejamento  
**então** comunico 

## Observações
Links de apoio e informações adicionais

**Comment by Clarisse1983** [comment]
Fechando, porque setembro já foi ;)
