### ISSUE TITLE
Cobertura da Apresentação do FeliciLab no 25º Concurso de Inovação no Setor Público da Enap

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/FeliciLab#201]
## **Objetivo**

**Como** Como comunicadores do FeliciLab  
**Quero** Iremos colaborar na cobertura da apresentação do FeliciLab no 25º Concurso de Inovação no Setor Público da Enap
**Para** Produzir registros em foto e documentar esse momento para divulgação posterior e para memória do FeliciLab e da ESP.

## **Contexto**

- O FeliciLab, Laboratório de Inovação da Diretoria de Inovação da Escola de Saúde Pública do Ceará - ESP, é finalista no 25º Concurso de Inovação no Setor Público da Enap. A apresentação final, realizada pelo Assessor de Inovação Uirá Porã, será feita através de videoconferência no dia 16 de setembro de 2021, as 14h30. Colaboradores do FeliciLab e da ESP`irão acompanhar esta apresentação ao vivo, no auditório da ESP, e através da plataforma de videoconferência ZOOM.

## **Escopo**

DesignLab
- [x] Produzir registros fotográficos
- [x] Realizar o tratamento digital das imagens
- [x] Disponibilizar uma pasta no Drive com os arquivos finais

**Comment by danielgula** [comment]
Ok. A issue foi transferida para o repo Felicilab e instanciada no Project do Publicilab.

**Comment by pauloamoreira** [comment]
@uira e @Clarisse1983, tarefa concluída. arquivos de fotos disponíveis em pasta no drive do PubliciLab. segue link para visualização: https://drive.google.com/drive/folders/12u_-k4xNoqlkKGaISko-6QLPVQLxL0SC?usp=sharing
