### ISSUE TITLE
[Edição 3] Produzir ReuniãoZONA

### ISSUE THREAD

**Issue by anapvcv** [EscolaDeSaudePublica/FeliciLab#234]
## **Objetivo**

**Como** participante do Publicilab 
**Quero** apoiar a produção do Edição 3 da ReuniãoZONA
**Para** fortalecer os encontros que proporcionados pelo Felicilab

## **Contexto**

-   A Reuniãozona é um momento de encontro presencial geral com todo o time, para atualização e diálogo sobre os processos de trabalho em curso, principais informes, etc. A terceira edição será em dezembro.

## **Publicilab**

- [x] Definir data: 17/12, a tarde
- [x] Criar agenda
- [x] Fechar programação
- [x] Atualizar arte (data e hora)
- [x] Fazer release sobre a programação
- [x] Produzir apresentação das entregas do NIT/Felicilab em 2021
- [x]  Enviar release à Ascom e solicitar divulgação e cobertura do evento
- [x]  Mobilizar pessoas (divulgação no Telegram, envio de email e mobilização por telefone - Nicolas)
- [x] Cobertura fotográfica 
- [x] Criar Vivência para o evento

## **Grupo tático**

- [x]  Definir programação do encontro

## Observações
Links de apoio e informações adicionais
https://www.figma.com/file/RUHP1EdXZ1GX70w71Nql71/Mapeamento-de-Entregas-NIT%2FFelicilab?node-id=0%3A1

**Comment by geniltonfaheinajr** [comment]
A data depende da definição do evento geral da ESP/CE. Alice vai se informar com ADINS e DIAFI.
