### ISSUE TITLE
Campanha de divulgação do Edital 26

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/FeliciLab#244]
## **Objetivo**

**Como** profissional inovador
**Quero** receber a campanha para o Edital 26
**Para** me inscrever e participar da inovação aberta em saúde

## **Contexto**

- O Edital 26 possui 49 perfis profissionais desejados a se tornarem bolsistas das soluções digitais da ESP nos próximos 12 meses. É preciso construir uma campanha que possa  atingir esse público-alvo diverso, em pouco tempo, informando como essa pessoa deve se inscrever e participar do certame, garantindo assim uma grande adesão.

## **Escopo**

- [x] Mapeamento dos Articuladores (Raianny)
- [x] Briefing com Informações Principais (Sara e Clarisse)
- [x] Release para divulgação (Ascom)
- [x] Live sobre o Edital (Ascom)
- [x] Página do edital no Site Felicilab (Daniel)
- [x] FAQ do edital no site (Daniel)
- [x] Tutorial Mapa (Ana)
- [x] Reels #vempraesp
- [x] Cards divulgação geral (Ascom)
- [x] Cards divulgação dos perfis (Ascom)

## **Critérios de Aceitação**

**Dado que** estou procurando oportunidades de trabalho
**Quando** recebo informações da campanha do Edital 26
**então** me inscrevo no certame

## Observações
[Links de apoio e informações adicionais](https://docs.google.com/document/d/13Tmw9q21WoVvMs-Vz8Icc7sMmX7BfcCHenj4Paeey8U/edit#heading=h.jgxhaxkn8t55)

**Comment by raiannyqz** [comment]
@saracafe vai elaborar termos de uso de imagens, para assinatura das pessoas que aparecem nas artes
https://drive.google.com/drive/folders/1sau8HnDRjZ4fnogpAxWAS8AvkvPdgkFR
