### ISSUE TITLE
Emissão de declaração online de participação em cursos e eventos

### ISSUE THREAD

**Issue by ricardopoppi** [EscolaDeSaudePublica/FeliciLab#308]
## **Objetivo**

**Eu como** gestor de curso
**Quero** emitir declaração online de participação em cursos e eventos
**Para** reduzir o tempo e custo na emissão de declarações

## **Contexto**

- Permitir a emissão de declaração online para todos os alunos que tenham obtido os critérios necessários para aprovação nos cursos e eventos (frequência, notas etc)
- Disponibilizar a declaração para os alunos (conectado com épica xxx)

## **Escopo UX**
Issue 1
- [ ] Mapear os critérios de aceitação com persona
Regras de negócio das declarações e certificados: https://www.figma.com/file/nd1WwdaSNtpOIu4bChpttX/Principal?node-id=3695%3A3673

Issue 2 (Tarefas que também atendem ao DEV)
- [ ] Formular a experiência para emissão das declarações, considerando as regras de negócio dos cursos/eventos (Sagu)
- [ ] Desenhar as telas para a emissão das declarações (Sagu)

## **Escopo Narrativas**

- [ ] Revisar comunicação/textos (substituir loren ipsuns) uma vez finalizada a proposta de jornada com telas pelo designlab

## **Escopo DEV**

- [ ] Implementar/ajustar API no Sagu para disponibilizar os critérios/status de aprovação/reprovação para outros sistemas
- [ ] Estudo para emissão do certificado com assinador digital (Serpro)
- [ ] Desenvolver as telas da funcionalidade de emissão de declaração para os alunos

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] título
**Dado que**
**Quando** 
**então** 

## Observações
Time UX:
Link do fluxo/experiência/telas

## Observações
Links de apoio e informações adicionais

## Histórico

Tarefas e fatias

Pauta de validação com a Ana (prévia a sprint):
- Validar com a Ana por qual módulo começar en/pe/ex ou residencia ou multi. 
- Pedir pra Ana os modelos de certificados referentes aos cursos de cada módulo.
- Entender a demanda da impressão e registro sob a ótica da assinatura digital gov.br. É só para os avaliadores?
- Validar com Ana se descentraliza ou mantem na sec academica a emissão dos certificados. O acesso pode ser descentralizado com os gestores de curso.

Tarefas mapeadas até o momento:

- Produção das telas no mapas para o aluno poder gerar o documento do certificado dentro das inscrições (1 sprint)

- Definir o(s) modelo(s) de certificado(s) para cada módulo do sagu (1 sprint)

- Produção das telas do sagu com uma segunda tela com o botão de gerar certificado para os alunos quando o curso estiver fechado. Aparecer uma ação (botão) abrir uma página com a lista de todos os aprovados da turma fechada e a partir dela o usuário gestor poder gerar os certificados. (1 sprint)

- Levantar informação sobre a api do assinador permitir assinar lote de documentos (1 sprint)

- Analisar consumo em disco e propor alternativas de armazenamento dos certificados se for o caso (1 sprint)

- Analisar a melhor arquitetura para que um agente autenticado pelo gov.br possa assinar um documento gerado pelo sagu e "devolver" para o sagu. (1 sprint)

- Implementar no core do SAGU a funcionalidade (que inclui as telas) para o usuário da sec academica gerar o documento do certificado (pré-assinatura) para os alunos, após o fechamento da turma (2 sprints)

- Customizar o plugin sagu-integration para permitir a disponibilização/exibição do certificado emitido no sagu para o aluno na área da inscrição do referido curso (1,5 sprint)

- [FORA DE ESCOPO] Customizar o plugin sagu-integration para gerar um selo associado ao agente aluno no mapa referente àquele certificado (1,5 sprint)

- Envio de certificado por email para os alunos (1 sprint)

Caminho escolhido:

Unicamente pelo Mapa. Porque, mesmo na opção do iSUS, seria pelo Mapa. A pessoa passa a ter opção de ver o certificado pelo Mapa, ou através de um selo. Já o gestor iria ver toda a oportunidade pelo mapa, mas com a emissão de certificado/assinatura pelo Sagu, via integração com o assinador Gov.br. Integração pelo iSUS seria uma fatia seguinte - o futuro seria que o iSUS proporcionasse isso, em um proximo momento. 

para o mapa emitir certificado: implementar um novo plugin e não usar o sistema de selos

Para o isus, trabalhar as notificações da história das inscrições, integrando com o mapa

Segunda sessão 27/06

Opção 1: 
Usuário fazer tudo pelo iSUS (integrar o processo de inscrição no iSUS e o processo de emissão de certificado). Envolver integração do iSUS com Mapa e com o Sagu.
Gestor gerencia as inscrições no mapa e a emissão de certificado no SAGU.

Opção 2: Usuário fazer tudo pelo mapa. Inscrição já é no mapa basta integrar a parte do Sagu para emissão de certificado
Gestor gerencia as inscrições no mapa e a emissão de certificado no SAGU.

Arquitetura: 

Opção 1: Desenvolver no SAGU a integração com o assinador do gov.br, vale usuários nível no login gov.br

Opção 2: Desenvolver uma aplicação para guarda e validação de certificados acoplada ao SAGU que é onde tem a fonte de dados. Essa aplicação pode usar o acesso ao assinador gov.br

Primeira sessão 21/06
Opção 1: Fazer a emissão dos certificados diretamente pelo usuário via mapas usando uma funcionalidade parecida com a dos selos usada atualmente (a partir da atribuição do selo pelo gestor do curso, lendo dados da API do Sagu)

Opção 2: Fazer a emissão dos certificados pelo iSUS incluindo a integração do iSUS com o mapa para que os alunos se inscrevam no iSUS também. A liberação dos certificados seria feita a partir da lista de "aprovados no curso" oriunda da API do SAGU

Opção 3: Desenvolver uma aplicação para guarda e validação de certificados acoplada ao SAGU que é onde tem a fonte de dados. Uma vez emitido o certificado gerar um selo no mapa para acesso ao certificado.

Opção 4: Desenvolver uma aplicação para guarda e validação de certificados acoplada ao SAGU que é onde tem a fonte de dados. Uma vez emitido o certificado o usuário acessa o certificado pelo iSUS. Também será necessária a integração do iSUS com o mapa para que os alunos se inscrevam no iSUS quando a oportunidade for aberta.

### Wanderley

Quais certificados?
Selo do mapa que emite declaração
secretaria academica
Ana Xenofonte vai saber os tipos de certificados e quando pode ser digital ou não

Sobre a ESPvirtual
Referenciou a Ana Xenofonte de novo, acredita que é manual
Moodle gera certificado (não tem detalhes)
Cleiton e Alex tem mais contexto sobre emissão de certificados pelo moodle

Cadastramento de participação em eventos
Pelo mapa é via oportunidade limpando os selecionados
Pelo sagu ou outro processo Wanderley não tem conhecimento mas Ana Xenofonte tem

Nazka
Certificados fora mapa: abre turma no sagu, cadastra manualmente nome a nome, atualiza frequencia no sagu manualmente a cada aula. Ao final do curso fecha o cadeadinho do curso, gera relatórios, são enviados pra sec academica e solicita a emissão de certificado que são feitos manualmente (no word) e é assinado pelo diretor da área e do superintendente (processo toma 1 mês). Nessa modalidade um selo físico é colado no papel.

Sobre o fluxo
A dor maior é da secretaria academica
Como não tem integração do SAGU com o mapa é manual e aí perde-se o controle
Alunos só emitem certificados diretamente no mapa (via selo) ou via ESPvirtual (moodle)

Thais
Samia é a pessoa que mais tem dor no contexto das inscrições de alunos. Porque? fez um curso com 2k-4k inscrições, público agentes de saúde, fez tudo via mapas, passou por muitas dores no mapa nesse processo

Nazka
Residência tem uma tipologia específica de certificados e declarações

Regimento escolar tem diretrizes para declarações e certificados
[https://app.zenhub.com/files/239431925/a9585eb2-ed8b-4f5b-9712-b703b4514d22/download](https://app.zenhub.com/files/239431925/a9585eb2-ed8b-4f5b-9712-b703b4514d22/download)

### Cleyton

O processo da ESPVirtual vai manualmente para o SAGU
acha que a certificação deveria sair pelo sistema do SAGU
No passado havia integração entre sagu e moodle
hoje é manual via csv

ideal seria ter o certificado validado
o moodle emite declarações atualmente (carga horária menor)
para que o moodle possa emitir certificados precisa ter a certificação digital
não há integração com o SAGU
o setor responsável pelo curso na ESPvirtual emite os relatórios das turmas para que isso seja levado manualmente ao SAGU
há a possibilidade do arquivo do certificado é emitido em pdf e enviado para a secretaria acadêmica
hoje a emissão é feita via relatório do moodle enviando para a sec academica para emissão em papel+selo
o moodel também poderia emitir, tem funcionalidade pra isso com qr code, detalhes de livro etc
moodle emite diplomas de cursos técnicos

### Ana Xenofonte

-Locais onde o certificado é emitido? 
 
O processo é feito todo manual. Segundo a Ana, nenhuma plataforma estar emitindo certificado hoje.  
 
-Quais os modelos de certificado? 
 
Cada área solicitante do curso pede um padrão diferente. Mas existe dados em comum compartilhados entre eles no certificado, como "Aluno, curso, carga-horária, Realizador(pode ser a ESP ou alguma parceria), local e no verso vem o programa do curso(essa informação tá no SAGU)" 
 
 
Esp.virtual: Estão emitindo certificado por lá?  
 
Não 
 
Esp.virtual: Os dados estão sendo alimentados no SAGU? 
 
sim. Ela exporta dados dos selecionados 
 
Sobre a questão da autenticação, qual a dor? 
 
1) Ana falou que a proposta do VIO da serpro foi apresentada em 2020. Foram feitas reuniões e acordos com o serpro, o processo estava caminhado e ela se sente frustrada por não saber pq parou; e pelo oq entendi estar finalizando agora em julho o "contrato" desse serviço do VIO 
 
2) Outro ponto é que tem que validar com a governância a questão de substituir a assinatura do superintendente por outro método de autenticação 
 
3) Existe também a questão do "registro": informação que consta no certificado que serve para emissão de 2° via. Esse registro precisa ser salvo fisicamente em livros para o processo de credenciamento (pode ser impresso).  
 
Quais módulos do SAGU emite certificado? 
 
O processo de emissão de certificado é feito apenas no ensino, pesquisa e extensão. Basicamente é dentro de uma modalidade denominada cursos livres que a ESP tem autorização para emitir essas declarações e certificado.  
 
O que precisa ser obrigatório na exportação MAPA -> SAGU no processo de matricula? 
 
nome 
sobrenome 
data de nascimento 
endereço 
formação profissional 
CPF 
 
Outras questões levantadas pela Ana fora do escopo:  
 
-Como seria o processo de criação de uma oportunidade no MAPA(quem defini se emite ou não declaração)? 
 
-A quem recorrer para atender a  demanda de criação de oportunidade no MAPA? 
 
-Ela falou sobre um projeto "calendário no google agendas", que ta esperando um resposta do Uirá sobre como proceder agora.

**Comment by RaniGub** [comment]
Refinar história

**Comment by caldy94** [comment]
Acabei de parear com o @victorMagalhaesPacheco a respeito dessa issue. Ele me comentou que cursos e eventos possuem seus certificados gerados de forma separada. No caso de cursos, o status do aluno (aprovado/reprovado) é mostrado no Sagu e o certificado é feito de forma manual pela Ana Xenofonte. Já no caso de eventos, a emissão dos certificados não está relacionada ao Sagu. @ricardopoppi e @matheuscpl, sugiro conversarmos novamente com o @victorMagalhaesPacheco para que possamos ver o andamento dessa issue, e aguardaremos uma resposta da Ana Xenofonte para a @carolynemaciente.

**Comment by ricardopoppi** [comment]
epica sendo fechada devido a termos criados as outras épicas das fatias
