### ISSUE TITLE
Resgate de declarações de forma virtual pelos alunos

### ISSUE THREAD

**Issue by ricardopoppi** [EscolaDeSaudePublica/FeliciLab#309]
## **Objetivo**

Eu **como** estudante
**Quero** resgatar minhas declarações de forma virtual
**Para** não precisar ter que ir até a ESP-CE

## **Contexto**

- Permitir o resgate de declarações pelos alunos que concluiram os cursos/eventos atendendo os requisitos, de forma virtual

## **Escopo UX**

- [ ] Entrevistar uma persona real de diretor/diretora de área
- [ ] Formular a experiência para resgate das declarações, considerando as regras de negócio dos cursos/eventos (Sagu)
- [ ] Desenhar as telas para o resgate das declarações (Sagu)

## **Escopo Narrativas**

- [ ] Revisar comunicação/textos (substituir loren ipsuns) uma vez finalizada a proposta de jornada com telas pelo designlab

## **Escopo DEV**

- [ ] Desenvolver as telas da funcionalidade de resgate de declaração para os alunos

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação DEV**

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

## Observações
Links de apoio e informações adicionais

**Comment by ricardopoppi** [comment]
deprecada pois na nova arquitetura o resgate é pelo mapa
