### ISSUE TITLE
[Certificados FATIA 0] Emissão de certificados digitais para os cursos livres módulo ensino/pesquisa/extensão do Sagu

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/FeliciLab#343]
## **Objetivo**

**Eu como** gestor de curso
**Quero** emitir declaração online de participação em cursos e eventos
**Para** reduzir o tempo e custo na emissão de declarações

## **Contexto**

- Permitir a emissão de declaração online no SAGU para todos os alunos que tenham obtido os critérios necessários para aprovação em oportunidades no Mapa da saúde. A declaração será um documento em PDF que pode ser em lote ou não para ser assinada em outro ambiente. 

## **Escopo UX**

- [x] Criar e validar certificado template com o assinatura do superintendente.
- [ ] Desenvolver telas e fluxo de processos para emissão do certificado pelo SAGU

## **Escopo DEV**

- [ ] Implementar funcionalidade de emissão de certificado no SAGU (em lote ou não) para ser assinado em outro ambiente
- [ ] Desenvolver ambiente em homologação para assinar em lote certificados emitidos pelo SAGU 

## Observações
Links de apoio e informações adicionais
